name: Replant
version: 2.0.1
main: org.achymake.replant.Replant
api-version: "1.21"
authors: [AchyMake, gamingjovi]
softdepend: [WorldGuard]
commands:
  replant:
    description: Replant main command
    usage: "/replant <reload|info>"
    permission: replant.command
permissions:
  replant.use:
    description: Allows using replant in general
    default: true
  replant.use.hand:
    description: Allows replanting with an empty hand
    default: true
  replant.use.hoe:
    description: Allows replanting with a hoe
    default: true
  replant.command:
    description: Allows /replant
    default: op
  replant.command.reload:
    description: Allows /replant reload
    default: op
  replant.bypass.worlds:
    description: Bypass world allow/deny list
    default: op
  replant.bypass.regions:
    description: Bypass region allow/deny list
    default: op
